avaron/urls.py
from django.conf.urls import url

from . import views
from .models import Game
app_name='avaron'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^(?P<game_room_num>[0-9]+)/$', views.game_room, name='game_room'), #Actual game room, directed from make_player
    url(r'^make_game/$', views.make_game, name='make_game'), #make game, generate room_num
    url(r'^make_player/$', views.make_player, name='make_player'), #makes player and game
    url(r'^(?P<game_num>[0-9]+)/(?P<round_num>[0-9]+)/$', views.start_game, name='start_game'),
    url(r'^GameClosed/', views.game_closed, name='game_closed'),
    url(r'^\d+/GetPlayers/', views.send_players, name ='send_players'),
    url(r'^GetGames/', views.send_games, name ='send_games'),
]

game1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^avaron/', include('avaron.urls')),
    url(r'^admin/', admin.site.urls),
]

avaron/models.py
from __future__ import unicode_literals

from django.db import models

class Game(models.Model):
	room_num = models.IntegerField()
	pub_date = models.DateTimeField('date created')
	game_started = models.BooleanField(default=0)
	rules_v = models.CharField(max_length=200, default='[]') #visibility matrix
	rules_t = models.CharField(max_length=200, default='[]') #role mapping index to name
	rules_wl = models.CharField(max_length=200, default='[]') #win lose conditions, i.e. mission details
	def __str__(self):
		return "Room num: " + str(self.room_num)
class Player(models.Model):
	game = models.ForeignKey(Game, on_delete=models.CASCADE)
	name = models.CharField(max_length=20)
	role = models.IntegerField()
	seed = models.BigIntegerField(default = 0)
	visible = models.CharField(max_length = 200, default='[]') #the guys this guy can see
	team = models.CharField(max_length=20, default='na') #which team
	msg = models.CharField(max_length=20, default='na') #The message the user sees
	def __str__(self):
		return "Name: " + self.name +" Game: " + str(self.game.room_num) + "Seed: " + str(self.seed)

avaron/forms.py
from django import forms
class PlayerForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    game = forms.IntegerField()
    role = forms.BooleanField()

    def clean_role(self): #validation check
    	data=self.cleaned_data['role']
    	if data>1:
    		raise ValidationError(_('Invalid role - Must be 1 or 0'))
    	return data

avaron/views.py
from django.shortcuts import render
# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .models import Game, Player
from django.utils import timezone
from django.urls import reverse
from .forms import PlayerForm
from django.shortcuts import get_object_or_404
from random import randint
import random
import math
import json
#TODO
#start game function, game logic to assign roles
#leave game
#delete game when all leave

def index(request):
    latest_game_list = Game.objects.filter(game_started=0).order_by('-pub_date')
    template = loader.get_template('avaron/index.html')
    context = {
        'latest_game_list': latest_game_list,
    }
    request.session['gameEntry']="na"
    return HttpResponse(template.render(context, request))

def game_closed(request):
    template = loader.get_template('avaron/gameClosed.html')
    context={}
    return HttpResponse(template.render(context, request))

def game_room(request, game_room_num):
	test=request.session['gameEntry']
	if test==int(game_room_num): #properly entered game (not typing in url)
		g=Game.objects.filter(room_num=game_room_num) #Game ID =/= Game room num, find the game that has the same room num
		players = Player.objects.filter(game=g) #Using g, we can find the players in the game properly since game compares id's
		template = loader.get_template('avaron/gameroom.html')
		context = {
			'players': players,
			'game': game_room_num, #'name' is the name of the variable that can be used in the html file through {{ name }}
		}
		return HttpResponse(template.render(context,request))
	else: #send user to bad join screen
		template = loader.get_template('avaron/badjoin.html')
		context = {}
		return HttpResponse(template.render(context, request))
#join game
def make_player(request):
	if (request.method=='POST' and request.is_ajax()):
		form = PlayerForm(request.POST)
		#gets the values submitted in the template
		player_name=request.POST.get('pname')
		game_num=request.POST.get('num')
		gamelist = Game.objects.filter(room_num=game_num) #for more help, seek Django QuerySet API
		if not gamelist: #game doesn't exist, stop joining
			data={'gameNumber':-1} #gameNumber = -1 indicates game doesn't exist
			return HttpResponse(json.dumps(data),content_type='application/json')
		g=get_object_or_404(gamelist) #isolates the already existing game
		if int(g.game_started)==0: #game hasn't started
			seed=randint(1,90001) #seed will be used for randomization
			p=Player.objects.create(game=g,name=player_name,role=0,seed=seed)
			p.save() #creates players with game among other things
			request.session['id']=seed #to identify player
			request.session['gameEntry']=int(game_num) #Adds a cookie/session to indicate a legit entry
			data={'gameNumber':game_num}
			return HttpResponse(json.dumps(data),content_type='application/json')
			# return HttpResponseRedirect('/avaron/%s' % game_num) #Redirects to game room
		else: #game has already started, send to sorry page
			data={'gameNumber':0}
			return HttpResponse(json.dumps(data),content_type='application/json')
	else:
		form = PlayerForm()
		return HttpResponseRedirect('/avaron/%s' % game_num) #Redirects to game room

#create game
def make_game(request):
	if (request.method=='POST' and request.is_ajax()):
		form = PlayerForm(request.POST)
		#gets the name submitted in the template
		player_name=request.POST.get('pname')
		gamelist = Game.objects.all() #gets all existing games
		roomnums=[]
		for game in gamelist:
			roomnums.append(int(game.room_num)) #create an array of all existing game_num's
		new_num=1+max(roomnums) #simply add 1 to largest current game_num and this is our new game_num
		visibilityR=[
		[[-1,-1,0,0,0],[-1,-1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]],
		[[-1,-1,0,0,0,0],[-1,-1,0,0,0,0],[0,-1,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]],
		[[-1,-1,-1,0,0,0,0],[-1,-1,-1,0,0,0,0],[-1,-1,-1,0,0,0,0],[0,-1,-1,1,0,0,0],[0,0,-1,-1,1,0,0],[0,0,0,0,0,1,0],[0,0,0,0,0,0,1]],
		[[-1,-1,-1,0,0,0,0,0],[-1,-1,-1,0,0,0,0,0],[-1,-1,-1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1]],
		[[-1,-1,-1,0,0,0,0,0,0],[-1,-1,-1,0,0,0,0,0,0],[-1,-1,-1,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,0],[0,0,0,0,1,0,0,0,0],[0,0,0,0,0,1,0,0,0],[0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,0,1]]
		]
		RoleNames=[
		["Bad Guy1","Bad Guy2","Good Guy 3","Good Guy 4","Good Guy 5"],
		["Known bad guy - you are hidden so far from good guys","Bad Guy - one good guy sees you","Smart Good guy - You see one bad","Good Guy 1","Good Guy 2","Good Guy 3"],
		["Mordrid","Assassin","Morgana","Merlin","Percival","Dumb Blue 1","Dumb Blue 2"],
		["Bad Guy","Bad Guy","Bad Guy","Good Guy","Good Guy","Good Guy","Good Guy","Good Guy"],
		["Bad Guy","Bad Guy","Bad Guy","Good Guy","Good Guy","Good Guy","Good Guy","Good Guy","Good Guy"]
		]
		g=Game.objects.create(room_num=new_num,pub_date=timezone.now(),
			game_started=0,rules_v=visibilityR,rules_t=RoleNames)
		g.save() #creates game
		seed=randint(1,90001)
		p=Player.objects.create(game=g,name=player_name,role=0,seed=seed)
		p.save() #creates player
		request.session['id']=seed #to identify player
		request.session['gameEntry']=int(new_num)
		data={'gameNumber':new_num}
	else:
		print("ohno")
		form = PlayerForm()
	return HttpResponse(json.dumps(data),content_type='application/json')
	#return HttpResponseRedirect('/avaron/%s' % new_num) #Redirects to game room
#send a list of players as a json to js file
def send_players(request):
	if (request.method=='POST' and request.is_ajax()):
		game_num=request.POST.get('num')
		g=Game.objects.filter(room_num=int(game_num))
		players = Player.objects.filter(game=g) #players in game
		plist=[]
		for player in players:
			plist.append(player.name)
		data={'players':plist}
		return HttpResponse(json.dumps(data),content_type='application/json')
#send a list of numbers of all open games as a json to js file
def send_games(request):
	if (request.method=='POST' and request.is_ajax()):
		g=Game.objects.filter(game_started=0) #all open games
		glist=[]
		for game in g:
			glist.append(game.room_num)
		data={'games':glist}
		return HttpResponse(json.dumps(data),content_type='application/json')
#in game
def start_game(request, game_num, round_num):
	g=Game.objects.filter(room_num=game_num).first()
	players = Player.objects.filter(game=g).order_by('seed') #players in game, sorted
	if int(g.game_started)==0: #first person to press start game
	# ------ ASSIGN ROLES ---------
		visibR=eval(str(g.rules_v)) #come back to this one day
		NameR=eval(str(g.rules_t))
		for i in range(0,len(visibR)): #choose appropriate game rules based off player count
			if(players.count()==len(visibR[i])):
				visibR=visibR[i]
				NameRules=NameR[i]
				break
		i=0
		for player in players: #assign roles(num) and team to players
			player.role=i #player is number i
			player.team=visibR[i][i]
			player.visible=visibR[i]
			player.save()
			i=i+1
		for player in players: # Write player msg to display to the user.
			VisibNames=[]
			for j in range(0,len(player.visible)):
				#find the name
				if player.visible[j]==-1 and j!=player.role:
					namedP = Player.objects.filter(role=j,game=g)
					VisibNames.append(namedP.first().name)
			random.shuffle(VisibNames)
			player.msg=VisibNames
			player.save()
		g.game_started=1
		g.rules_t=NameRules
		g.save()
	# ------------------------------
	our_seed = request.session['id']
	your_guy=Player.objects.filter(seed=our_seed).first()
	NameR=eval(str(g.rules_t))
	YourRole = NameR[your_guy.role]
	formatVis=""
	for i in eval(str(your_guy.msg)):
		formatVis=formatVis+str(i)+"\n"
	template = loader.get_template('avaron/ingame.html')
	context = {
		'players': players,
		'your_guy': your_guy,
		'game': game_num,
		'round_num': round_num,
		'visible': formatVis,
		'role_name': YourRole,
	}
	return HttpResponse(template.render(context,request))

avaron/templates/avaron/badjoin.html
<!DOCTYPE html>
<html>
<head>
<title>Avaron Game</title>
{% load static %}
<link href="{% static 'avaron/lobby.css' %}" rel="stylesheet" type="text/css"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
	<p><montserratb>ERR....</montserratb></p>
	<p><montserratb>TRY TO PROPERLY JOIN/CREATE A GAME THROUGH LOBBY BUTTONS</montserratb></p>
</body>
<form action = "{% url 'avaron:home' %}" method="post">
{% csrf_token %}
<input type="submit" value="back to lobby">
</form>
</html>

avaron/templates/avaron/gameClosed.html
<!DOCTYPE html>
<html>
<head>
<title>Avaron Game</title>
{% load static %}
<link href="{% static 'avaron/lobby.css' %}" rel="stylesheet" type="text/css"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
	<p><montserratb>ERR....</montserratb></p>
	<p><montserratb>GAME ALREADY STARTED...SORRY</montserratb></p>
</body>
<form action = "{% url 'avaron:home' %}" method="post">
{% csrf_token %}
<input type="submit" value="back to lobby">
</form>
</html>

avaron/templates/avaron/gameroom.html
<!DOCTYPE html>
<html>
<head>
<title>Avaron Game</title>
{% load static %}
<link href="{% static 'avaron/lobby.css' %}" rel="stylesheet" type="text/css"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script src="{% static 'avaron/ingame.js' %}?v=00003" type="text/javascript"/></script>
<script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"/></script>
</head>
<body>
	<p id="gameHeader"></p>
	<p id="gamenum"><montserratb>{{ game }}</montserratb></p>
    <ul id="playerList">
    </ul>
</body>
<form>
<input type="button" onClick="history.go(0)" value="&#x21ba;">
</form>
<form action = "{% url 'avaron:start_game' game 1 %}" method="post">
{% csrf_token %}
<input type="submit" value="start game">
<p></p>
</form>
<form action = "{% url 'avaron:home' %}" method="post">
{% csrf_token %}
<input type="submit" value="back to lobby">
</form>
</html>

avaron/templates/avaron/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Avaron Game</title>
  {% load static %}
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  
  <link href="{% static 'avaron/normalize.css' %}" rel="stylesheet">
  <link href="{% static 'avaron/skeleton.css' %}" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"/></script>
  <script src="{% static 'avaron/main.js' %}?v=00001" type="text/javascript"/></script>
</head>

<body>
	{% csrf_token %}
  <div class="container">
    <div class="row">
      <div class="eight columns offset-by-two" style="margin-top: 3%">
        <h4 class="bigcenter">AVARON GAME LOBBY</h4>
      </div>
    </div>
  </div>

  <div class="container">
  	<div class="row" id="games">
  		<div class="four columns offset-by-four" style="margin-top:3%">
        <p style="text-align: center">Open Games:</p>
        <ul id="openGames" class="openGamesC">   
        </ul>
  		</div>
  	</div>
  </div>

  <div class="container">
  	<div class="row">
  		<div class="six columns offset-by-three" style="margin-top: 3%">
  			<div class="cardb">
  				<form method="post" onsubmit="myButton.disabled = true; return true;">
  					<h1>player name</h1>
  					<input id="player_name" type="text" name="player_field">
  					<h1>game code</h1>
  					<input id="game_num" type="text" name="game_field"><br>
  					<input class="button-primary" type="submit" id="join" value="join game">
  				</form>
          <p id="JoinError" style="color: #ef3245"></p>
  			</div>
  		</div>
  	</div>
  	<br>
  	<div class="row">
  		<div class="six columns offset-by-three" style="margin-top: 3%">
  			<div class="cardr">
  				<form method="post" onsubmit="myButton.disabled = true; return true;">
					<h1>player name</h1>
					<input id="player_nameC" type="text" name="player_field"><br>
  					<input class="button-primary" type="submit" value="create game" id="red">
  				</form>
  			</div>
  		</div>
  	</div>
  </div>
  <br><br><br>
  <section class="footer">
    <div class="row">
      <div class="twelve columns" style="margin-top: 1%">
        <p><br><br>2017 Avaron</p>
      </div>
    </div>
  </section>

</body>
</html>

avaron/templates/avaron/ingame.html
<!DOCTYPE html>
<html>
<head>
<title>Avaron Game</title>
{% load static %}
<link href="{% static 'avaron/lobby.css' %}" rel="stylesheet" type="text/css"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
	{% csrf_token %}
	<p><montserratb>Round Number {{ round_num }}:</montserratb></p>
    <p><montserrat>You: {{ your_guy.name }}</montserrat></p>
    <montserrat><p>~~~~~~~~~~~~</p></montserrat>    
    Role: {{ role_name}}<br>
	You are on team: {{your_guy.team}} <br>
	You see:{{visible}}
</body>

<form action = "{% url 'avaron:home' %}" method="post">
{% csrf_token %}
<input type="submit" value="back to lobby">
</form>
</html>